<a href="https://colab.research.google.com/github/kachhadiyaraj15/pytorch_deep_learning/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Hello Everyone,
#### I hope you all are doing extremely well. I am very excitd about PyTorch journey.

In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt



In [2]:
print(torch.__version__)

2.0.1+cu118


### Introducction to Tensor

In [5]:
# scaler
scaler = torch.tensor(7)

In [6]:
scaler.ndim   # it's (ndim) define number of sqaure bracket

0

In [7]:
# get tensor back to python int
scaler.item()

7

In [8]:
# Vector
vector = torch.tensor([7,7])

In [9]:
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [15]:
# MATRIX
MATRIX = torch.tensor([[1,2],
                      [2,3]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX.shape     # it's count number of square breacket with element

torch.Size([2, 2])

In [19]:
# Tensor

TENSOR = torch.tensor([[[1,2,3],
                        [2,3,4]],
                       [[1,2,4],
                       [3,4,5]]])

In [20]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([2, 2, 3])

### Random Tensor

- Torch random tensor - https://pytorch.org/docs/stable/generated/torch.rand.html

In [28]:
# Create random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2748, 0.8856, 0.0080, 0.4431],
        [0.5457, 0.8690, 0.9554, 0.3221],
        [0.6966, 0.5881, 0.2088, 0.3434]])

In [24]:
random_tensor.ndim

2

In [32]:
# Create random tensor with same shape to an image tensor
random_image_size_tensor = torch.rand(size= (224,224,3))    # Height,Widrth,Color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros ans Ones

In [33]:
zeros = torch.zeros(size = (3,4))

In [34]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
## Create a tenxor of ones
ones = torch.ones(size = (3,4))

In [38]:
ones * random_tensor

tensor([[0.2748, 0.8856, 0.0080, 0.4431],
        [0.5457, 0.8690, 0.9554, 0.3221],
        [0.6966, 0.5881, 0.2088, 0.3434]])

In [39]:
ones.dtype

torch.float32

### Creatinf a range of tensors and tensors-like

In [44]:
one_to_ten = torch.arange(0,11)

In [50]:
one_to_twenty = torch.arange(start = 0, end = 50 , step=3)

In [51]:
# Create tensors like
torch_zeros_like = torch.zeros_like(one_to_twenty)

In [52]:
print(one_to_ten)
print(one_to_twenty)
print(torch_zeros_like)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


## TENSOR  Datatypes
Torch Data types - https://pytorch.org/docs/stable/tensor_attributes.html

In [54]:
# float 32 tensors
float_32_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype = None)
float_32_tensor.dtype

torch.float32

In [55]:
float_16_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype = torch.float16 )
float_16_tensor.dtype

torch.float16

In [56]:
float_32_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype = None,
                               device = None,
                               requires_grad= False)
float_32_tensor.dtype

torch.float32

In [57]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [58]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.])

In [60]:
int_32_tensor =  torch.tensor([1,2,3], dtype = torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [61]:
float_32_tensor * int_32_tensor

tensor([1., 4., 9.])

In [62]:
print(float_32_tensor.dtype)
print(float_32_tensor.shape)
print(float_32_tensor.device)


torch.float32
torch.Size([3])
cpu


In [63]:
float_32_tensor + int_16_tensor

tensor([2., 4., 6.])

In [66]:
matrix = torch.rand(size = (3,4))
matrix_mm = torch.mm(matrix, matrix.T)   # mm is duplicate version of matmul function
matrix_mm

tensor([[1.4868, 1.3469, 1.3252],
        [1.3469, 1.2662, 1.1732],
        [1.3252, 1.1732, 1.5528]])