<a href="https://colab.research.google.com/github/kachhadiyaraj15/pytorch_deep_learning/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Hello Everyone,
#### I hope you all are doing extremely well. I am very excitd about PyTorch journey.

In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt



In [2]:
print(torch.__version__)

2.0.1+cu118


### Introducction to Tensor

In [3]:
# scaler
scaler = torch.tensor(7)

In [4]:
scaler.ndim   # it's (ndim) define number of sqaure bracket

0

In [5]:
# get tensor back to python int
scaler.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])

In [7]:
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[1,2],
                      [2,3]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape     # it's count number of square breacket with element

torch.Size([2, 2])

In [13]:
# Tensor

TENSOR = torch.tensor([[[1,2,3],
                        [2,3,4]],
                       [[1,2,4],
                       [3,4,5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([2, 2, 3])

### Random Tensor

- Torch random tensor - https://pytorch.org/docs/stable/generated/torch.rand.html

In [16]:
# Create random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3032, 0.7445, 0.5136, 0.9610],
        [0.0755, 0.1026, 0.9988, 0.0843],
        [0.8901, 0.6081, 0.8895, 0.3549]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create random tensor with same shape to an image tensor
random_image_size_tensor = torch.rand(size= (224,224,3))    # Height,Widrth,Color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros ans Ones

In [19]:
zeros = torch.zeros(size = (3,4))

In [20]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
## Create a tenxor of ones
ones = torch.ones(size = (3,4))

In [23]:
ones * random_tensor

tensor([[0.3032, 0.7445, 0.5136, 0.9610],
        [0.0755, 0.1026, 0.9988, 0.0843],
        [0.8901, 0.6081, 0.8895, 0.3549]])

In [24]:
ones.dtype

torch.float32

### Creatinf a range of tensors and tensors-like

In [25]:
one_to_ten = torch.arange(0,11)

In [26]:
one_to_twenty = torch.arange(start = 0, end = 50 , step=3)

In [27]:
# Create tensors like
torch_zeros_like = torch.zeros_like(one_to_twenty)

In [28]:
print(one_to_ten)
print(one_to_twenty)
print(torch_zeros_like)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


## TENSOR  Datatypes
Torch Data types - https://pytorch.org/docs/stable/tensor_attributes.html

In [29]:
# float 32 tensors
float_32_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype = None)
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype = torch.float16 )
float_16_tensor.dtype

torch.float16

In [31]:
float_32_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype = None,
                               device = None,
                               requires_grad= False)
float_32_tensor.dtype

torch.float32

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [33]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.])

In [34]:
int_32_tensor =  torch.tensor([1,2,3], dtype = torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [35]:
float_32_tensor * int_32_tensor

tensor([1., 4., 9.])

In [36]:
print(float_32_tensor.dtype)
print(float_32_tensor.shape)
print(float_32_tensor.device)


torch.float32
torch.Size([3])
cpu


In [37]:
float_32_tensor + int_32_tensor

tensor([2., 4., 6.])

In [38]:
matrix = torch.rand(size = (3,4))
matrix_mm = torch.mm(matrix, matrix.T)   # mm is duplicate version of matmul function
matrix_mm

tensor([[1.6455, 0.9772, 1.3649],
        [0.9772, 0.5975, 0.8533],
        [1.3649, 0.8533, 1.9440]])

### Reshaping, stacking, squeezing and unsqueezing tensors

| Method	| One-line description |
|---------| ---------------------|
|torch.reshape(input, shape) |	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().|
|Tensor.view(shape)|	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.|
|torch.stack(tensors, dim=0)|	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.|
|torch.squeeze(input)	|Squeezes input to remove all the dimenions with value 1.|
|torch.unsqueeze(input, dim)|	Returns input with a dimension value of 1 added at dim.|
|torch.permute(input, dims)	|Returns a view of the original input with its dimensions permuted (rearranged) to dims.|

In [39]:
x = torch.arange(1., 10.)

In [40]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
# add extra dimention
y = x.reshape(9,1)

In [42]:
y

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [43]:
z = x.view(1,9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [44]:
# # Changing z changes x
z [:, 0] = 5
z, x


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [45]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [46]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [47]:
# To do so you can use torch.squeeze() (I remember this as squeezing the tensor to only have dimensions over 1)
x_squeeze = torch.squeeze(x)
x_squeeze, x_squeeze.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [48]:
x_unsqueeze = torch.unsqueeze(x_squeeze, dim = 0)
x_unsqueeze, x_unsqueeze.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [49]:
x_unsqueeze = torch.unsqueeze(x_squeeze, dim = 1)
x_unsqueeze, x_unsqueeze.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [50]:
# torch.permute operation, chanfge the dimension based on requirement
x_permute = torch.permute(x_unsqueeze, (1,0))
print(x_permute)
print(f"X_unsqueeze shape: {x_unsqueeze.shape}")
print(f"X_permute shape: {x_permute.shape}")

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
X_unsqueeze shape: torch.Size([9, 1])
X_permute shape: torch.Size([1, 9])


In [51]:
x = torch.randn(2, 3, 5)
x.size()
torch.permute(x, (2, 0, 1)).size()

torch.Size([5, 2, 3])