<a href="https://colab.research.google.com/github/kachhadiyaraj15/pytorch_deep_learning/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Hello Everyone,
#### I hope you all are doing extremely well. I am very excitd about PyTorch journey.

In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt



In [2]:
print(torch.__version__)

2.0.1+cu118


### Introducction to Tensor

In [5]:
# scaler
scaler = torch.tensor(7)

In [6]:
scaler.ndim   # it's (ndim) define number of sqaure bracket

0

In [7]:
# get tensor back to python int
scaler.item()

7

In [8]:
# Vector
vector = torch.tensor([7,7])

In [9]:
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [15]:
# MATRIX
MATRIX = torch.tensor([[1,2],
                      [2,3]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX.shape     # it's count number of square breacket with element

torch.Size([2, 2])

In [19]:
# Tensor

TENSOR = torch.tensor([[[1,2,3],
                        [2,3,4]],
                       [[1,2,4],
                       [3,4,5]]])

In [20]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([2, 2, 3])

### Random Tensor

- Torch random tensor - https://pytorch.org/docs/stable/generated/torch.rand.html

In [28]:
# Create random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2748, 0.8856, 0.0080, 0.4431],
        [0.5457, 0.8690, 0.9554, 0.3221],
        [0.6966, 0.5881, 0.2088, 0.3434]])

In [24]:
random_tensor.ndim

2

In [32]:
# Create random tensor with same shape to an image tensor
random_image_size_tensor = torch.rand(size= (224,224,3))    # Height,Widrth,Color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros ans Ones

In [33]:
zeros = torch.zeros(size = (3,4))

In [34]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
## Create a tenxor of ones
ones = torch.ones(size = (3,4))

In [38]:
ones * random_tensor

tensor([[0.2748, 0.8856, 0.0080, 0.4431],
        [0.5457, 0.8690, 0.9554, 0.3221],
        [0.6966, 0.5881, 0.2088, 0.3434]])